CRYPTOAUTHLIB_DIR := ../cryptoauthlib/lib

COMPONENT_SRCDIRS := $(CRYPTOAUTHLIB_DIR)/atcacert

COMPONENT_OBJS := $(CRYPTOAUTHLIB_DIR)/atcacert/*.o

COMPONENT_ADD_INCLUDEDIRS := $(CRYPTOAUTHLIB_DIR)


